# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\rsensorservice\"\"\n\rSensorRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"3\n\x0eSensorResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x0c\n\x04unit\x18\x02 \x01(\t2W\n\x06Sensor\x12M\n\x0eGetTemperature\x12\x1c.sensorservice.SensorRequest\x1a\x1d.sensorservice.SensorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=31
  _globals['_SENSORREQUEST']._serialized_end=65
  _globals['_SENSORRESPONSE']._serialized_start=67
  _globals['_SENSORRESPONSE']._serialized_end=118
  _globals['_SENSOR']._serialized_start=120
  _globals['_SENSOR']._serialized_end=207
# @@protoc_insertion_point(module_scope)
